timestamp: 2021-03-25T16:27:59.309021
process title: pantsd [/home/nathan/odl/ol-django]
sys.argv: ['/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/bin/pants', '--pants-bin-name=./pants', '--pants-version=2.3.0', 'package', 'src/python/mitol/common:mitol-django-common']
pid: 124689
Exception caught: (pants.engine.internals.scheduler.ExecutionError)
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/bin/local_pants_runner.py", line 246, in run
    engine_result = self._perform_run(goals)
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/bin/local_pants_runner.py", line 167, in _perform_run
    return self._perform_run_body(goals, poll=False)
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/bin/local_pants_runner.py", line 184, in _perform_run_body
    return self.graph_session.run_goal_rules(
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/init/engine_initializer.py", line 130, in run_goal_rules
    exit_code = self.scheduler_session.run_goal_rule(
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/engine/internals/scheduler.py", line 568, in run_goal_rule
    self._raise_on_error([t for _, t in throws])
  File "/home/nathan/.cache/pants/setup/bootstrap-Linux-x86_64/2.3.0_py38/lib/python3.8/site-packages/pants/engine/internals/scheduler.py", line 536, in _raise_on_error
    raise ExecutionError(

Exception message: 1 Exception encountered:

  MappingError: Failed to parse src/python/mitol/common/BUILD:
invalid syntax (<string>, line 36)


